### ISSUE TITLE
Add an index.html file

### ISSUE THREAD

**Issue by ibnesayeed** [urduweb/dictionary-scans#3]
To avoid 404 on the root URL, add an index.html file.

**Comment by owenvoke** [comment]
@ibnesayeed do you mean in the root of the repo, or in the root of the folders? 😄 
If so, I'd be happy to do this.

~~Would you like it to have a directory list of the different files in each folder?~~
Maybe not considering there are a ton of files.

**Comment by ibnesayeed** [comment]
@PXgamer thanks for the interest. Only the root of the site needs an index file. However, the content of that file are not documented in this issue, so it would be difficult fill it in for those who are unaware of it. I have just fixed it locally and the code push is on it's way. I really appreciate your interest though.

**Comment by owenvoke** [comment]
No problem. I'll keep this on watch.
